version: '3.8'

services:
  api:
    image: sakura/shortener-api
    container_name: ShortenerApi
    ports:
      - "8080:8080"
    restart: always
    environment:
      - MONGODB_URI
    networks:
      - vhost
      - mongo

networks:
    vhost:
      external: true
    mongo:
      external: true